name: Hazmat Panther
favicon: null
layout_spectrum: 0.5015353672206402
typography_spectrum: 0.41153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d09'
    - '#e5e2db'
    - '#464e4a'
    - '#7f8181'
    - '#b6b3b2'
  brandStrength: 0.9682718957774341
  lightness: 0.20384648232720792
  saturation: 0.07782036811113358
  rhythmicContrast: 0.05850070738233626
purpose: []
