name: Hazmat Panther
favicon: null
layout_spectrum: 0.5015353672206402
typography_spectrum: 0.5647685010917485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9682718957774341
  lightness: 0.20384648232720792
  saturation: 0.07782036811113358
  rhythmicContrast: 0.05850070738233626
purpose: []
